development:
  shopify_api_key: "c67c6718da87efdf792547a6bb83a3c7"
  shopify_secret: "046a6fc5252d1d85602eea6d1aac558f"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://localhost:3000'
  pre_fix_url: ''
production:
  shopify_api_key: "451764caaf0b9381ce3f3ce39b641e0a"
  shopify_secret: "d3d5d13d1309a63867c01996e629fa17"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://ec2-52-88-152-46.us-west-2.compute.amazonaws.com'
  pre_fix_url: '/apps'